Repository garri-ribeiro/garri.codes, pull requests merged in 2020-05, with the labels that each got.

#15 Test kodiak
  .kodiak.toml
Labels: automerge

#16 New configs kodiak
  .kodiak.toml
Labels: automerge, deploy-this-PR

#17 ola mundo
  .kodiak.toml
Labels: deploy-this-PR

#19 test-kodak-4
  gatsby-config.js
Labels: deploy-this-PR

#20 test-kodak-5
  gatsby-node.js
Labels: deploy-this-PR

#21 test-kodak-6
  gatsby-ssr.js
Labels: deploy-this-PR

#23 test-kodak-8
  gatsby-browser.js
Labels: deploy-this-PR

#24 kodiak conflict 1
  src/components/intro/Intro.js
Labels: deploy-this-PR

#27 kodiak conflict 4
  src/components/intro/Intro.js
Labels: deploy-this-PR

#26 kodiak conflict 3
  src/components/intro/Intro.js
Labels: deploy-this-PR
